from __future__ import annotations

import logging
from pathlib import Path

from .llm import chat_json
from .models import ContributorPlaybook, PRFact, PRStats

logger = logging.getLogger("init.pr_pattern_analyzer")

PROMPT_DIR = Path(__file__).parent / "prompts"


def _format_facts(facts: list[PRFact]) -> str:
    """Serialize PRFacts into a compact, human-readable block for the LLM."""
    parts: list[str] = []
    for f in facts:
        body_preview = f.body[:300].replace("\n", " ") if f.body else "(empty)"
        parts.append(
            f"PR #{f.pr_number}: {f.title}\n"
            f"  labels: {', '.join(f.labels) if f.labels else '(none)'}\n"
            f"  sha: {f.sha}\n"
            f"  files: {f.files_changed} (+{f.insertions} -{f.deletions})\n"
            f"  scope: {f.scope}\n"
            f"  tests: {'yes' if f.has_tests else 'no'}"
            f"  docs: {'yes' if f.has_docs else 'no'}"
            f"  changelog: {'yes' if f.has_changelog else 'no'}"
            f"  readme: {'yes' if f.has_readme else 'no'}\n"
            f"  time_to_merge: {f.time_to_merge_hours:.1f}h\n"
            f"  review_rounds: {f.review_rounds}\n"
            f"  linked_issue: {'yes' if f.linked_issue else 'no'}\n"
            f"  title_conventional: {'yes' if f.title_conventional else 'no'}\n"
            f"  body: {body_preview}"
        )
    return "\n\n".join(parts)


def compute_stats(facts: list[PRFact]) -> PRStats:
    """Compute deterministic aggregate stats from a list of PRFacts."""
    n = len(facts)
    if n == 0:
        return PRStats(
            min_time_to_merge_hours=0.0,
            max_time_to_merge_hours=0.0,
            min_files_changed=0,
            max_files_changed=0,
            min_insertions=0,
            max_insertions=0,
            min_deletions=0,
            max_deletions=0,
            min_review_rounds=0,
            max_review_rounds=0,
        )
    merge_times = [f.time_to_merge_hours for f in facts]
    files = [f.files_changed for f in facts]
    insertions = [f.insertions for f in facts]
    deletions = [f.deletions for f in facts]
    return PRStats(
        min_time_to_merge_hours=round(min(merge_times), 1),
        max_time_to_merge_hours=round(max(merge_times), 1),
        min_files_changed=min(files),
        max_files_changed=max(files),
        min_insertions=min(insertions),
        max_insertions=max(insertions),
        min_deletions=min(deletions),
        max_deletions=max(deletions),
        min_review_rounds=min(f.review_rounds for f in facts),
        max_review_rounds=max(f.review_rounds for f in facts),
    )


def _playbook_schema() -> dict:
    """Return a JSON Schema dict for ContributorPlaybook (for vLLM structured outputs).

    Strips the ``stats`` field — it is computed deterministically and not
    generated by the LLM.
    """
    schema = ContributorPlaybook.model_json_schema()
    # Remove stats from the schema so the LLM doesn't try to generate it.
    props = schema.get("properties", {})
    props.pop("stats", None)
    required = schema.get("required", [])
    if "stats" in required:
        required.remove("stats")
    # vLLM structured_outputs expects a top-level JSON Schema object.
    # Pydantic generates $defs for nested models — inline them so vLLM gets a
    # flat, self-contained schema.
    defs = schema.pop("$defs", {})
    if defs:
        _inline_defs(schema, defs)
    return schema


def _inline_defs(node: dict, defs: dict) -> None:
    """Recursively replace ``$ref`` pointers with their resolved definitions."""
    if isinstance(node, dict):
        ref = node.pop("$ref", None)
        if ref is not None:
            name = ref.rsplit("/", 1)[-1]
            if name in defs:
                node.update(defs[name])
                _inline_defs(node, defs)
            return
        for v in node.values():
            if isinstance(v, (dict, list)):
                _inline_defs(v, defs)
    elif isinstance(node, list):
        for item in node:
            if isinstance(item, (dict, list)):
                _inline_defs(item, defs)


def build_playbook(facts: list[PRFact], repo: str) -> ContributorPlaybook:
    """Single LLM call that synthesizes a ContributorPlaybook from PRFacts.

    Stats are computed deterministically from the facts and injected after
    the LLM generates the qualitative content.
    """
    stats = compute_stats(facts)
    system_prompt = (PROMPT_DIR / "synthesis.txt").read_text(encoding="utf-8")
    user_content = (
        f"REPOSITORY: {repo}\n\nMERGED PRS ({len(facts)} total):\n\n"
        + _format_facts(facts)
    )

    data = chat_json(
        system_prompt, user_content, max_output_tokens=4096, schema=_playbook_schema()
    )

    if not isinstance(data, dict):
        logger.warning(
            "Playbook synthesis returned no usable JSON; falling back to empty playbook."
        )
        return ContributorPlaybook(
            summary="",
            recommendations=[],
            checklist=[],
            example_prs=[],
            prs_analyzed=len(facts),
            repo=repo,
            stats=stats,
        )

    result: dict = data

    # Unwrap single-key wrapper if present
    fields = set(ContributorPlaybook.model_fields) - {"stats"}
    if not (fields & set(result)) and len(result) == 1:
        inner = next(iter(result.values()))
        if isinstance(inner, dict) and (fields & set(inner)):
            result = inner

    # Inject deterministic stats (LLM does not generate these)
    result["stats"] = stats.model_dump()

    try:
        return ContributorPlaybook.model_validate(result)
    except Exception as exc:  # noqa: BLE001
        logger.warning("Playbook validation failed: %s | data=%s", exc, result)
        return ContributorPlaybook(
            summary="",
            recommendations=[],
            checklist=[],
            example_prs=[],
            prs_analyzed=len(facts),
            repo=repo,
            stats=stats,
        )
